blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/parobek/DropDeck/tree/main/docs
    about: Check our documentation before opening an issue
  - name: Discussions
    url: https://github.com/parobek/DropDeck/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
